server:
  port: 8088

jenkins:
  enabled: true
  masters:
    - name: jenkins
      address: http://jenkins-service:8080
      username: jenkins
      password: jenkins

travis:
  enabled: false

dockerRegistry:
  enabled: true
  accounts:
    - name: docker
      address: https://quay.io
      username: moondev

      repositories:
        - spinnaker/clouddriver
        - spinnaker/front50
      # cacheThreads: # optional (default is 1) number of threads to cache registry contents across
      # clientTimeoutMillis: # optional (default is 1 minute) time before the registry connection times out
      # paginateSize: # optional (default is 100) number of entries to request from /_catalog at a time


redis:
  connection: redis://redis-service:6379

services:
  clouddriver:
    baseUrl: http://clouddriver-service:7002
  echo:
    baseUrl: http://echo-service:8089

clouddriver:
  baseUrl: http://clouddriver-service:7002
echo:
  baseUrl: http://echo-service:8089