bakery:
  allowMissingPackageInstallation: true
  baseUrl: http://rosco-service:8087
  extractBuildDetails: true
  roscoApisEnabled: true
  propagateCloudProviderType: true

rosco:
  baseUrl: http://rosco-service:8007
  roscoApisEnabled: true
  enabled: true
  allowMissingPackageInstallation: true

default:
  bake:
    account: docker

  securityGroups: null
  vpc:
    securityGroups: null
echo:
  baseUrl: 8089
  enabled: false
flex:
  baseUrl: http://not-a-host
front50:
  baseUrl: http://front50-service:8080

igor:
  enabled: false
  baseUrl: http://igor-service:8088
kato:
  baseUrl: http://clouddriver-service:7002
mort:
  baseUrl: http://clouddriver-service:7002
oort:
  baseUrl: http://clouddriver-service:7002
redis:
  connection: redis://redis-service:6379
server:
  port: 8083
services:
  orca:
    timezone: west
tasks:
  executionWindow:
    timezone: west
tide:
  baseUrl: http://not-a-host
  enabled: false
